/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MoCodeEditor: typeof import('./../components/edit/MoCodeEditor.vue')['default']
    MoEditDialog: typeof import('./../components/grid/components/MoEditDialog.vue')['default']
    MoGrid: typeof import('./../components/grid/MoGrid.vue')['default']
    MoIcon: typeof import('./../components/icons/MoIcon.vue')['default']
    MoPagination: typeof import('./../components/grid/components/MoPagination.vue')['default']
    MoSearch: typeof import('./../components/grid/components/MoSearch.vue')['default']
    MoTable: typeof import('./../components/grid/components/MoTable.vue')['default']
    MoToolbar: typeof import('./../components/grid/components/MoToolbar.vue')['default']
  }
}
